version: "3.8"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./sz_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
